### ISSUE TITLE
状态栏

### ISSUE THREAD

**Issue by GaGa-cloud** [J-JasonZz/ANVideoPlayer#1]
视频播放时，状态栏怎么隐藏不了呢？大神

**Comment by ZhenKaiJia** [comment]
设置下status bar优先级

**Comment by J-JasonZz** [comment]
全屏播放的时候状态栏是隐藏掉的，小窗的时候状态栏是显示的

**Comment by J-JasonZz** [comment]
infoPlist里面设置View controller-based status bar appearance为NO
